### ISSUE TITLE
cd -<number>

### ISSUE THREAD

**Issue by spacekookie** [oh-my-fish/plugin-cd#3]
In zsh you can do `cd -2` to basically run `cd -` twice. Would you care to add that to this plugin as well?

**Comment by SanCoder-Q** [comment]
@spacekookie Sorry for the late reply. Turns out zsh maintains a stack to store the navigation history. And it is not hard for fish. I will develop this [feature](https://www-s.acm.illinois.edu/workshops/zsh/cd.html) very soon.

**Comment by SanCoder-Q** [comment]
Done
